// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: touch.proto

package touch

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TouchReply_TouchType int32

const (
	TouchReply_TAP     TouchReply_TouchType = 0
	TouchReply_SWIPE   TouchReply_TouchType = 1
	TouchReply_RELEASE TouchReply_TouchType = 2
)

// Enum value maps for TouchReply_TouchType.
var (
	TouchReply_TouchType_name = map[int32]string{
		0: "TAP",
		1: "SWIPE",
		2: "RELEASE",
	}
	TouchReply_TouchType_value = map[string]int32{
		"TAP":     0,
		"SWIPE":   1,
		"RELEASE": 2,
	}
)

func (x TouchReply_TouchType) Enum() *TouchReply_TouchType {
	p := new(TouchReply_TouchType)
	*p = x
	return p
}

func (x TouchReply_TouchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TouchReply_TouchType) Descriptor() protoreflect.EnumDescriptor {
	return file_touch_proto_enumTypes[0].Descriptor()
}

func (TouchReply_TouchType) Type() protoreflect.EnumType {
	return &file_touch_proto_enumTypes[0]
}

func (x TouchReply_TouchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TouchReply_TouchType.Descriptor instead.
func (TouchReply_TouchType) EnumDescriptor() ([]byte, []int) {
	return file_touch_proto_rawDescGZIP(), []int{0, 0}
}

type TouchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    TouchReply_TouchType `protobuf:"varint,1,opt,name=type,proto3,enum=touch.TouchReply_TouchType" json:"type,omitempty"`
	X       int32                `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y       int32                `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Contact int32                `protobuf:"varint,4,opt,name=contact,proto3" json:"contact,omitempty"`
	Ts      int64                `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *TouchReply) Reset() {
	*x = TouchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_touch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TouchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchReply) ProtoMessage() {}

func (x *TouchReply) ProtoReflect() protoreflect.Message {
	mi := &file_touch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchReply.ProtoReflect.Descriptor instead.
func (*TouchReply) Descriptor() ([]byte, []int) {
	return file_touch_proto_rawDescGZIP(), []int{0}
}

func (x *TouchReply) GetType() TouchReply_TouchType {
	if x != nil {
		return x.Type
	}
	return TouchReply_TAP
}

func (x *TouchReply) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TouchReply) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TouchReply) GetContact() int32 {
	if x != nil {
		return x.Contact
	}
	return 0
}

func (x *TouchReply) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type TouchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TouchRequest) Reset() {
	*x = TouchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_touch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TouchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchRequest) ProtoMessage() {}

func (x *TouchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_touch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchRequest.ProtoReflect.Descriptor instead.
func (*TouchRequest) Descriptor() ([]byte, []int) {
	return file_touch_proto_rawDescGZIP(), []int{1}
}

func (x *TouchRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_touch_proto protoreflect.FileDescriptor

var file_touch_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x6f, 0x75, 0x63, 0x68, 0x22, 0xb1, 0x01, 0x0a, 0x0a, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x2e, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x22, 0x2c, 0x0a, 0x09, 0x54, 0x6f,
	0x75, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x41, 0x50, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x53, 0x57, 0x49, 0x50, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52,
	0x45, 0x4c, 0x45, 0x41, 0x53, 0x45, 0x10, 0x02, 0x22, 0x28, 0x0a, 0x0c, 0x54, 0x6f, 0x75, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x3d, 0x0a, 0x05, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x12, 0x34, 0x0a, 0x08, 0x54,
	0x6f, 0x75, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x13, 0x2e, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x2e,
	0x54, 0x6f, 0x75, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x74,
	0x6f, 0x75, 0x63, 0x68, 0x2e, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x30,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_touch_proto_rawDescOnce sync.Once
	file_touch_proto_rawDescData = file_touch_proto_rawDesc
)

func file_touch_proto_rawDescGZIP() []byte {
	file_touch_proto_rawDescOnce.Do(func() {
		file_touch_proto_rawDescData = protoimpl.X.CompressGZIP(file_touch_proto_rawDescData)
	})
	return file_touch_proto_rawDescData
}

var file_touch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_touch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_touch_proto_goTypes = []interface{}{
	(TouchReply_TouchType)(0), // 0: touch.TouchReply.TouchType
	(*TouchReply)(nil),        // 1: touch.TouchReply
	(*TouchRequest)(nil),      // 2: touch.TouchRequest
}
var file_touch_proto_depIdxs = []int32{
	0, // 0: touch.TouchReply.type:type_name -> touch.TouchReply.TouchType
	2, // 1: touch.Touch.TouchReq:input_type -> touch.TouchRequest
	1, // 2: touch.Touch.TouchReq:output_type -> touch.TouchReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_touch_proto_init() }
func file_touch_proto_init() {
	if File_touch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_touch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TouchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_touch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TouchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_touch_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_touch_proto_goTypes,
		DependencyIndexes: file_touch_proto_depIdxs,
		EnumInfos:         file_touch_proto_enumTypes,
		MessageInfos:      file_touch_proto_msgTypes,
	}.Build()
	File_touch_proto = out.File
	file_touch_proto_rawDesc = nil
	file_touch_proto_goTypes = nil
	file_touch_proto_depIdxs = nil
}
