// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: jpeg.proto

package pics

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type JPEGReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length int32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Type   int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *JPEGReply) Reset() {
	*x = JPEGReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jpeg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JPEGReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JPEGReply) ProtoMessage() {}

func (x *JPEGReply) ProtoReflect() protoreflect.Message {
	mi := &file_jpeg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JPEGReply.ProtoReflect.Descriptor instead.
func (*JPEGReply) Descriptor() ([]byte, []int) {
	return file_jpeg_proto_rawDescGZIP(), []int{0}
}

func (x *JPEGReply) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *JPEGReply) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type JPEGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *JPEGRequest) Reset() {
	*x = JPEGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jpeg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JPEGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JPEGRequest) ProtoMessage() {}

func (x *JPEGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jpeg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JPEGRequest.ProtoReflect.Descriptor instead.
func (*JPEGRequest) Descriptor() ([]byte, []int) {
	return file_jpeg_proto_rawDescGZIP(), []int{1}
}

func (x *JPEGRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *JPEGRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JPEGRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_jpeg_proto protoreflect.FileDescriptor

var file_jpeg_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6a, 0x70, 0x65, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x69,
	0x63, 0x73, 0x22, 0x37, 0x0a, 0x09, 0x4a, 0x50, 0x45, 0x47, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x45, 0x0a, 0x0b, 0x4a,
	0x50, 0x45, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x32, 0x3a, 0x0a, 0x04, 0x4a, 0x50, 0x45, 0x47, 0x12, 0x32, 0x0a, 0x08, 0x53, 0x65,
	0x6e, 0x64, 0x4a, 0x50, 0x45, 0x47, 0x12, 0x11, 0x2e, 0x70, 0x69, 0x63, 0x73, 0x2e, 0x4a, 0x50,
	0x45, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x69, 0x63, 0x73,
	0x2e, 0x4a, 0x50, 0x45, 0x47, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jpeg_proto_rawDescOnce sync.Once
	file_jpeg_proto_rawDescData = file_jpeg_proto_rawDesc
)

func file_jpeg_proto_rawDescGZIP() []byte {
	file_jpeg_proto_rawDescOnce.Do(func() {
		file_jpeg_proto_rawDescData = protoimpl.X.CompressGZIP(file_jpeg_proto_rawDescData)
	})
	return file_jpeg_proto_rawDescData
}

var file_jpeg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jpeg_proto_goTypes = []interface{}{
	(*JPEGReply)(nil),   // 0: pics.JPEGReply
	(*JPEGRequest)(nil), // 1: pics.JPEGRequest
}
var file_jpeg_proto_depIdxs = []int32{
	1, // 0: pics.JPEG.SendJPEG:input_type -> pics.JPEGRequest
	0, // 1: pics.JPEG.SendJPEG:output_type -> pics.JPEGReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jpeg_proto_init() }
func file_jpeg_proto_init() {
	if File_jpeg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jpeg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JPEGReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jpeg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JPEGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jpeg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jpeg_proto_goTypes,
		DependencyIndexes: file_jpeg_proto_depIdxs,
		MessageInfos:      file_jpeg_proto_msgTypes,
	}.Build()
	File_jpeg_proto = out.File
	file_jpeg_proto_rawDesc = nil
	file_jpeg_proto_goTypes = nil
	file_jpeg_proto_depIdxs = nil
}
